Repository IOTNBO-Capstone/IOTNBO-FE, pull requests merged in 2022-12, with the labels that each got.

#41 Testing/refactor
  cypress/e2e/landing_page_spec.cy.js
  src/Components/LandingPage/LandingPage.js
Labels: help wanted

#42 Testing/data cy refactor
  cypress/e2e/individual_therapist_spec.cy.js
  cypress/e2e/landing_page_spec.cy.js
  cypress/e2e/outbound_spec.cy.js
  src/Components/App/App.js
  src/Components/Footer/Footer.js
  src/Components/LandingPage/LandingPage.js
  src/Components/OutboundLink/OutboundLink.js
  src/Components/TherapistPage/TherapistPage.js
Labels: refactor

#44 Refactor to improve accessibility
  cypress/e2e/landing_page_spec.cy.js
  src/Assets/Equilibrium-bkgd.png
  src/Assets/Equilibrium-bkgd.webp
  src/Components/LandingPage/LandingPage.js
  src/Components/TherapistCard/TherapistCard.js
  src/index.css
Labels: refactor

#48 Testing/stubbing
  cypress/e2e/individual_therapist_spec.cy.js
  cypress/e2e/landing_page_spec.cy.js
  cypress/e2e/outbound_spec.cy.js
  cypress/fixtures/data1.json
  cypress/support/commands.js
  cypress/util/graphql-utils.js
Labels: enhancement

#50 Add stubbing to error handling testing
  cypress/e2e/errorhandling_spec.cy.js
Labels: refactor

#51 Add cypress code coverage
  cypress.config.js
  cypress/support/e2e.js
  cypress/support/index.js
  instrumented/Components/App/App.js
  instrumented/Components/BadUrl/BadUrl.js
  instrumented/Components/ErrorMessage/ErrorMessage.js
  instrumented/Components/Footer/Footer.js
  instrumented/Components/LandingPage/LandingPage.js
  instrumented/Components/OutboundLink/OutboundLink.js
  instrumented/Components/TherapistCard/TherapistCard.js
  instrumented/Components/TherapistPage/TherapistPage.js
  instrumented/index.js
  instrumented/reportWebVitals.js
  instrumented/setupTests.js
  instrumented/utilities.js
  package-lock.json
  package.json
  src/Components/LandingPage/LandingPage.css
  src/Components/TherapistCard/TherapistCard.css
Labels: testing

#45 add CSS styling to OutboundLink
  src/Components/OutboundLink/OutboundLink.css
  src/Components/OutboundLink/OutboundLink.js
Labels: styling

#52 Refactor files to improve code coverage
  .nyc_output/e3b7e7f1-1ddc-4588-9602-4a4f74cda65a.json
  .nyc_output/out.json
  .nyc_output/processinfo/e3b7e7f1-1ddc-4588-9602-4a4f74cda65a.json
  .nyc_output/processinfo/index.json
  cypress/e2e/equilibrium_spec.cy.js
  src/Components/App/App.js
  src/Components/BadUrl/BadUrl.js
  src/Components/ErrorMessage/ErrorMessage.js
  src/Components/LandingPage/LandingPage.js
  src/Components/TherapistPage/TherapistPage.js
  src/reportWebVitals.js
Labels: refactor, testing

#53 Styling/refactor css
  .nyc_output/7b0194be-5226-4415-8181-93eb03458fd7.json
  .nyc_output/out.json
  .nyc_output/processinfo/7b0194be-5226-4415-8181-93eb03458fd7.json
  .nyc_output/processinfo/e3b7e7f1-1ddc-4588-9602-4a4f74cda65a.json
  .nyc_output/processinfo/index.json
  cypress/e2e/equilibrium_spec.cy.js
  cypress/e2e/individual_therapist_spec.cy.js
  cypress/e2e/outbound_spec.cy.js
  src/Assets/github.png
  src/Assets/linkedin.png
  src/Components/LandingPage/LandingPage.css
  src/Components/LandingPage/LandingPage.js
  src/Components/OutboundLink/OutboundLink.css
  src/Components/OutboundLink/OutboundLink.js
  src/Components/TherapistPage/TherapistPage.css
  src/Components/TherapistPage/TherapistPage.js
  src/index.css
Labels: bug, refactor, styling
